import code as x 
x.create("shavya",25)
x.create("src",70,3600) 
x.read("shavya")
x.read("src")
x.create("shavya",50)
x.modify("shavya",55)
x.delete("shavya")
t1=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t1.start()
t1.sleep()
t2=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t2.start()
t2.sleep()
